### ISSUE TITLE
Players using 1.20.2 are kicked

### ISSUE THREAD

**Issue by xPoyraz** [LoneDev6/BungeePackFix#49] opened 2023-10-26 20:52 UTC
```
[23:29:11] [Netty Worker IO Thread #14/WARN]: [/|PoyrazOglu] <-> DownstreamBridge <-> [Dunya5] - A decoder exception has been thrown:
io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 98301 (got 83457492 bytes)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 98301 (got 83457492 bytes)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:63) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:54) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.read(ClientboundResourcePackPacket.java:100) ~[?:?]
	at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.read(ClientboundResourcePackPacket.java:114) ~[?:?]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
	... 24 more
[23:29:11] [Netty Worker IO Thread #14/INFO]: [PoyrazOglu] disconnected with: Sunucu çöktü
[23:29:11] [Netty Worker IO Thread #14/INFO]: [/|PoyrazOglu] -> UpstreamBridge has disconnected
[23:29:11] [Netty Worker IO Thread #14/INFO]: [/|PoyrazOglu] <-> DownstreamBridge <-> [Dunya5] has disconnected
```

**Comment by LoneDev6** [comment] 2023-10-27 08:50
Did you set a very long custom message for your resourcepack?
It seems to be something related to that.

**Comment by SuprexDE** [comment] 2023-10-29 21:42
Same problem but I used the standard message from ItemsAdder

**Comment by nickynice1** [comment] 2023-10-30 23:15
I have the same problem. I am using default config. My players get randomly kicked all the time

**Comment by GabrielMoreiradeSouza** [comment] 2023-10-31 20:20
Hello,

I'm also experiencing a recurring issue on my server where players using version 1.20.2 are consistently disconnected and encounter the following console error:

io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

**Comment by SuprexDE** [comment] 2023-11-01 17:13
Here is a fixed version: https://suprexde.de/img/Vove1/GiPExAJE93.jar

Tested with the latest version of Paper and Waterfall (+ Geyser)

**Comment by GabrielMoreiradeSouza** [comment] 2023-11-03 00:55
The issue of players being kicked has been resolved with this version. However, we have identified a new problem where players on version 1.20.2 are unable to see the server texture, whereas those on version 1.20.1 can.

**Comment by petulikan1** [comment] 2023-11-12 15:23
net.md_5.bungee.protocol.FastDecoderException: Error decoding packet class ClientboundResourcePackPacket with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 06 b1 c3 99 01 ff ff fe 80 00 01 20 81 00       |........... ..  |
+--------+-------------------------------------------------+----------------+
Caused by: net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 98301 (got 2515377 bytes)
        at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:66) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:57) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.read(ClientboundResourcePackPacket.java:100) ~[?:?]
        at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.read(ClientboundResourcePackPacket.java:114) ~[?:?]
        at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:461) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:61) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fc0a27:unknown]
        at java.lang.Thread.run(Thread.java:833) [?:?]


Got possibly same error?

**Comment by LoneDev6** [comment] 2023-11-21 18:43
Probably.
Still no idea how to reproduce it, so I cannot fix it sadly.
I suspect it's caused by another plugin.

**Closed** 2024-01-09 16:39 UTC
Labels: type: bug
